### ISSUE TITLE
Duplicate tag "quickfix" in file vim-codesearch/doc/crcs.txt

### ISSUE THREAD

**Issue by anforowicz** [chromium/vim-codesearch#1]
Vundle reports the following error: Error running:

:helptags ~/.vim/bundle/vim-codesearch/doc

E154: Duplicate tag "quickfix" in file /blah/blah/.vim/bundle/vim-codesearch/doc/crcs.txt

**Comment by asankah** [comment]
Fixed in 8417869b9904d38239ba7a89639a909d970105b4. Thanks!
