### ISSUE TITLE
Multiple :CrCallgraph failing

### ISSUE THREAD

**Issue by sgraham** [chromium/vim-codesearch#5]
cd \src\cr\src
vim base\task_scheduler\scheduler_worker_pool_impl.cc
/Start  (to get to SchedulerWorkerPoolImpl::Start)
:CrCallgraph  (works fine, 7 refs)
Ctrl-O  (back to Start)
move down a few lines to AutoSchedulerLock
:CrCallgraph
Found a swap file by the name "c:/tmp//c%%src%cr%src%Callgraph.swp"
             dated: Wed Jun 07 15:20:27 2017
         file name: c:/src/cr/src/Callgraph
          modified: YES
         user name: scott   host name: RIVER-VAN
        process ID: 1039952
While opening file "Callgraph"

(1) Another program may be editing the same file.  If this is the case,
    be careful not to end up with two different instances of the same
    file when making changes.  Quit, or continue with caution.
(2) An edit session for this file crashed.
    If this is the case, use ":recover" or "vim -r Callgraph"
    to recover the changes (see ":help recovery").
    If you did this already, delete the swap file "c:/tmp//c%%src%cr%src%Callgraph.swp"
    to avoid this message.

"Callgraph"  24 lines --4%--
Error detected while processing function crcs#Callgraph:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\src\Dropbox\utils\vim-codesearch/vimsupport.py", line 50, in inner_call_wrapper
    return func(*args, **kwargs)
  File "c:\src\Dropbox\utils\vim-codesearch/vimsupport.py", line 314, in RunCallgraphSearch
    buffer_num = _SetupVimBuffer('call', 'Callgraph')
  File "c:\src\Dropbox\utils\vim-codesearch/vimsupport.py", line 113, in _SetupVimBuffer
    name=name, source_root=_GetCodeSearch().GetSourceRoot(), type=t))
vim.error: Vim(file):E325: ATTENTION
Press ENTER or type command to continue

Pressing ENTER takes me to the old results for Start, not those for AutoSchedulerLock.

**Comment by asankah** [comment]
Hmm. We are doing `setlocal buftype=nofile` which should result in there being no swapfile.

What's your Vim version?

**Comment by asankah** [comment]
Can't repro with Vim 7.4.8 or Neovim.

**Comment by sgraham** [comment]
Hmm, maybe I have some weird option locally that's making it do that then.

:ver
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 18:25:27)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-2
Compiled by mool@tororo

**Comment by asankah** [comment]
Oh. Windows! Repros for me on Windows.

**Comment by sgraham** [comment]
buftype=nofile is set for my buffer. Maybe it should be setting noswapfile? Dunno.

**Comment by asankah** [comment]
I added `noswapfile` in master. Try now?

**Comment by asankah** [comment]
An alternative is to open a new buffer with a unique buffer name for all searches. The current design is to only have one buffer of a specific type (i.e. at most one search buffer, at most one xref buffer and so forth). This was done to prevent proliferation of buffers. Perhaps it wasn't necessary.

**Comment by sgraham** [comment]
lgtm with noswapfile. Thanks for the quick iteration. :)
