### ISSUE TITLE
CrXrefSearch Can't determine signature still

### ISSUE THREAD

**Issue by cmumford** [chromium/vim-codesearch#8]
This is basically issue #4 but in a different file.

This **works**
1. Open `extensions/browser/extension_request_limiting_throttle.cc`.
2. Go to line 38 and move cursor above `throttling_entry_`.
3. :CrXrefSearch 

This **fails**
1. Above line 38 add a single comment.
2. Go down one line and move cursor above `throttling_entry_`.
3. :CrXrefSearch

vim-codesearch is at revision 179860a2863ffd.

**Comment by asankah** [comment]
Likely due to the recent codesearch behavior changes. Looking.

**Comment by asankah** [comment]
There's still some additional work to be done here before we can roll the new `codesearch-py`. I'll get to it soon.
